### ISSUE TITLE
Github Actions fails to build pycairo hence font build fails

### ISSUE THREAD

**Issue by mitradranirban** [googlefonts/googlefonts-project-template#180]
Though my font builds locally with same requirements.text, in github actions it fails with following output 
```
Collecting pycairo==1.27.0 (from -r requirements.txt (line 301))
  Downloading pycairo-1.27.0.tar.gz (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.5/661.5 kB 14.0 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-j9uw_vwt/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 1020, in wrapper
          return func(*args, **kwargs)
        File "/tmp/pip-build-env-j9uw_vwt/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 1042, in get_requires_for_build_wheel
          if os.environ.get('NINJA') is None and _env_ninja_command() is None:
        File "/tmp/pip-build-env-j9uw_vwt/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 997, in _env_ninja_command
          version = subprocess.run([ninja_path, '--version'], check=False, text=True, capture_output=True).stdout
        File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line [186](https://github.com/mitradranirban/samaano-fonts/actions/runs/11118786097/job/30892935282#step:7:187)3, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/samaano-fonts/samaano-fonts/venv/bin/ninja'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [Makefile:32: venv/touchfile] Error 1
Error: Process completed with exit code 2.
```
What may be wrong in build.yaml?

**Comment by mitradranirban** [comment]
It started after Github backend upgraded from ubuntu 22.04 (jammy) to 24.04 (noble). So it is probably a os specific issue

**Comment by mitradranirban** [comment]
Font is built only after commenting off the cache portion of build.yaml file

**Comment by simoncozens** [comment]
That makes sense. Users probably need to empty their caches after the upgrade. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#deleting-cache-entries

**Comment by mitradranirban** [comment]
So instruction should be there to empty the cache after each system upgrade

**Comment by janbrasna** [comment]
Interestingly there is no implicit expression for the actual OS used _(unofficially: https://github.com/actions/runner-images/discussions/7879),_ see e.g. this boilerplate to follow to get caches keyed on the OS version:
- https://github.com/actions/cache/discussions/1025

_(The issue with `-latest` runner labels migrating to different OS versions is that often you get runners from multiple resource pools assigned, jumping back and forth between runs:/…)_

Would it be helpful if this is added, say, to the toolset step, to include the OS version somehow in the cache key?
